[package]
name = "vinesapp"
version = "0.1.0"
description = "Vines"
authors = ["you"]
homepage = "https://github.com/lightningrodlabs/vines"
license = "CAL 1.0"
repository = ""
edition = "2021"
rust-version = "1.70"
resolver = "2"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]


[build-dependencies]
tauri-build = { version = "2.2.0", default-features = false , features = [] }

[dependencies]
serde = { version = "=1.0.219", default-features = false }
tauri = { version = "=2.9", default-features = false , features = [] }
tauri-plugin-holochain = { git = "https://github.com/darksoil-studio/tauri-plugin-holochain", branch = "main-0.6.1"}
tauri-plugin-clipboard-manager = "2.0.0"

holochain = { version = "0.6.1-rc", default-features = false, features = [ "sqlite-encrypted", "wasmer_sys", "transport-iroh" ] }
holochain_types = {version = "0.6.1-rc", default-features = false }

lair_keystore = { version = "0.6.3" }

log = "0.4"
tauri-plugin-log = "2.4.0"
tauri-plugin-opener = "2.2.7"
tauri-plugin-os = "2.2.1"
url2 = "0.0.6"
app_dirs2 = "2.5.5"
anyhow = "1"
serde_json = "1.0.120"
argon2 = "0.5.3"
sha2 = "0.10.8"
hex = "0.4.3"

#crabcamera = "0.4.0"
image = "0.25"
rqrr = "0.7"
base64 = "0.22"

[profile.dev]
incremental = true # Compile your binary in smaller steps.
opt-level = 0
debug = true

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.

[profile.dev.package."*"]
opt-level = 1
debug = false # workaround for "not enough space" issue on android
