[workspace]
resolver = "2"
members = [
    "dna/zomes/path_explorer",
    "dna/zomes/authorship_integrity",
    "dna/zomes/authorship_coordinator",
    "dna/zomes/authorship_zapi",
    "dna/zomes/profiles_integrity",
    "dna/zomes/profiles",
    "dna/zomes/threads_integrity",
    "dna/zomes/threads",
]
exclude = ["src-tauri"]

[workspace.package]
version = "0.1.0"
rust-version = "1.75.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "=1.0.228", default-features = false }
holochain_serialized_bytes = "=0.0.57"
hdi = { version = "=0.7.1", default-features = false }
hdk = { version = "=0.6.1", default-features = false }

zome_utils = { git = "https://github.com/ddd-mtl/zdk", branch = "main-0.6" }
zome_path = { git = "https://github.com/ddd-mtl/zdk", branch = "main-0.6" }
zome_signals = { git = "https://github.com/ddd-mtl/zdk", branch = "main-0.6" }
zome_core = { git = "https://github.com/ddd-mtl/zdk", branch = "main-0.6" }

time_indexing = { git = "https://github.com/ddd-mtl/zdk", branch = "main-0.6" }
path_explorer_types = { git = "https://github.com/ddd-mtl/zdk", branch = "main-0.6" }
path_explorer = { git = "https://github.com/ddd-mtl/zdk", branch = "main-0.6" }

hc_zome_profiles_integrity = { git = "https://github.com/holochain-open-dev/profiles", branch = "main-0.6" }
hc_zome_profiles_coordinator = {git = "https://github.com/ddd-mtl/zdk", branch = "main-0.6", package="profiles_alt_coordinator" }


[profile.dev]
lto = false
opt-level = 0
overflow-checks = false

[profile.release]
opt-level = "z"
#incremental = false
#codegen-units = 1
#panic = "abort"
#lto = true
lto = false
