/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "authorship" */
export const authorshipFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"ascribe_target",
	"ascribe_app_entry",
	"get_all_ascribed_types",
	"get_author",
	"get_all_ascribed_entries",
	"get_ascribed_type_children",

];


/** Generate tuple array of function names with given zomeName */
export function generateAuthorshipZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of authorshipFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zAuthorship" */
export const authorshipZomeFunctions: [ZomeName, FunctionName][] = generateAuthorshipZomeFunctionsArray("zAuthorship");
