/* This file is generated by zits. Do not edit manually */

export enum AuthorshipUnitEnum {
	Bogus = 'Bogus',
}

/**
 * -------------------------------------------------------------------------------------------------
 * Zome's link types
 * -------------------------------------------------------------------------------------------------
 */
export enum AuthorshipLinkType {
	AuthorshipPath = 'AuthorshipPath',
	Target = 'Target',
	Author = 'Author',
}
