/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "threads" */
export const threadsFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"get_original_author",
	"publish_any_bead",
	"fetch_any_bead",
	"fetch_many_any_beads",
	"publish_reaction",
	"unpublish_reaction",
	"pull_reactions",
	"publish_entry_bead",
	"publish_entry_as_bead",
	"create_entry_bead",
	"fetch_entry_bead",
	"fetch_many_entry_beads",
	"find_beads",
	"find_latest_beads",
	"publish_text_bead",
	"fetch_text_bead",
	"fetch_many_text_bead",
	"publish_text_bead_at",
	"publish_many_text_bead_at",
	"decrypt_my_bead",
	"decrypt_bead",
	"encrypt_bead",
	"publish_enc_bead",
	"fetch_enc_bead",
	"fetch_many_enc_beads",
	"probe_dm_threads",
	"publish_dm_thread",
	"publish_favorite",
	"unpublish_favorite",
	"probe_my_favorites",
	"commit_first_global_log",
	"query_global_log",
	"commit_update_global_log",
	"probe_all_latest",
	"probe_all_between",
	"probe_latest_items",
	"commit_thread_log",
	"query_thread_logs",
	"get_record_author",
	"get_data_type",
	"notify_peer",
	"probe_inbox",
	"unpublish_notification",
	"publish_notify_setting",
	"pull_my_notify_settings",
	"pull_notify_settings",
	"pull_pp_notify_settings",
	"fetch_pp",
	"probe_pps_from_subject_hash",
	"probe_pps_from_subject_anchor",
	"publish_participation_protocol",
	"query_all",
	"query_pps",
	"query_semantic_topics",
	"query_any_beads",
	"query_entry_beads",
	"query_text_beads",
	"query_enc_beads",
	"publish_semantic_topic",
	"pull_all_semantic_topics",
	"search_semantic_topics",
	"update_semantic_topic",
	"find_subjects_by_type",
	"find_subjects_for_applet",
	"find_subject_types_for_applet",
	"find_hide_link",
	"hide_subject",
	"unhide_subject",
	"probe_all_hiddens",
	"pull_all_subjects",
	"pull_applets",
	"cast_tip",
];


/** Generate tuple array of function names with given zomeName */
export function generateThreadsZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of threadsFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zThreads" */
export const threadsZomeFunctions: [ZomeName, FunctionName][] = generateThreadsZomeFunctionsArray("zThreads");
