/* This file is generated by zits. Do not edit manually */

export enum ThreadsUnitEnum {
	AnyBead = 'AnyBead',
	EntryBead = 'EntryBead',
	TextBead = 'TextBead',
	EncryptedBead = 'EncryptedBead',
	SemanticTopic = 'SemanticTopic',
	ParticipationProtocol = 'ParticipationProtocol',
	GlobalLastProbeLog = 'GlobalLastProbeLog',
	ThreadLastProbeLog = 'ThreadLastProbeLog',
}

/**
 * -------------------------------------------------------------------------------------------------
 * Link types
 * -------------------------------------------------------------------------------------------------
 */
export enum ThreadsLinkType {
	ReversePath = 'ReversePath',
	GlobalTimePath = 'GlobalTimePath',
	ThreadTimePath = 'ThreadTimePath',
	SemanticTopicPath = 'SemanticTopicPath',
	SubjectPath = 'SubjectPath',
	TimeItem = 'TimeItem',
	Topics = 'Topics',
	Threads = 'Threads',
	Beads = 'Beads',
	Protocols = 'Protocols',
	Invalid = 'Invalid',
	Inbox = 'Inbox',
	Hide = 'Hide',
	EmojiReaction = 'EmojiReaction',
	NotifySetting = 'NotifySetting',
	Favorite = 'Favorite',
	Dm = 'Dm',
}
