name: build-webhapps

on:
  workflow_call:

jobs:
  build-webhapps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install npm dependencies
      - name: Install npm dependencies
        shell: bash
        run: |
          npm install
      # install rust tools
      - name: install rust tools
        shell: bash
        run: |
          npm run install:rust
      # Download submodules
      - name: Download submodules
        shell: bash
        run: |
          npm run install:submodules
      # install hc tool
      - name: Install hc tool
        shell: bash
        run: |
          npm run install:hc
      # Install hash-zome
      - name: Install hash-zome
        run: |
          npm run install:hash-zome
      # Build Files happ
      - name: Build Files happ
        shell: bash
        run: |
          npm run build:files
      # Build happ
      - name: Build happ
        shell: bash
        run: |
          CARGO_NET_GIT_FETCH_WITH_CLI=true npm run build:happ
      # Localize
      - name: Localize
        run: |
          npm run extract:localize
          npm run build:localize
      # Build webapp
      - name: Build webapp
        run: |
          npm run build:webapp
      # Package web-happ
      - name: Package web-happ
        run: |
          npm run package:webapp
      # build we-applet
      - name: build we-applet
        shell: bash
        run: |
          npm run build -w we-applet
      # Package we-applet
      - name: Package we-applet
        shell: bash
        run: |
          npm run package:we
      # Regroup artifacts
      - name: Regroup artifacts
        run: |
          cp target/wasm32-unknown-unknown/release/*.wasm ./artifacts
      # List uploaded files
      - name: List uploaded files
        run: ls -R
        working-directory: ./artifacts
      # "upload" artifacts
      - uses: actions/upload-artifact@v4
        with:
          path: artifacts
